SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

CREATE TABLE IF NOT EXISTS `ASIAKKAAT` (
  `AVAIN` int(11) NOT NULL AUTO_INCREMENT,
  `KAYTTAJATUNNUS` varchar(50) NOT NULL,
  `SALASANA` varchar(50) NOT NULL,
  `NIMI` varchar(50) NOT NULL,
  `KAYNTIOSOITE` varchar(50) NOT NULL,
  `LASKUTUSOSOITE` varchar(50) NOT NULL,
  `PUHELINNUMERO` varchar(13) NOT NULL,
  `SAHKOPOSTI` varchar(50) NOT NULL,
  `ASUNTOTYYPPI` varchar(50) NOT NULL,
  `PINTAALA` varchar(50) NOT NULL,
  `TONTTIKOKO` varchar(50) NOT NULL,
  `LUONTIPVM` varchar(10) NOT NULL,
  PRIMARY KEY (`AVAIN`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

  INSERT INTO `ASIAKKAAT` (`AVAIN`, `KAYTTAJATUNNUS`, `SALASANA`) VALUES
  (1, 'admin', 'admin');
  INSERT INTO `ASIAKKAAT` (`AVAIN`, `KAYTTAJATUNNUS`, `SALASANA`, `NIMI`, `KAYNTIOSOITE`, `LASKUTUSOSOITE`, `PUHELINNUMERO`, `SAHKOPOSTI`, `ASUNTOTYYPPI`, `PINTAALA`, `TONTTIKOKO`, `LUONTIPVM`) VALUES
  (2, 'matti1', 'salasana', 'Matti Meikalainen', 'Jokukatu 16', 'Toimistokatu 1', '050 1122444', 'matti.meikalainen@sahkoposti.net','omakotitalo', '67m^2', '100m^2', '16-09-2013');
  INSERT INTO `ASIAKKAAT` (`AVAIN`, `KAYTTAJATUNNUS`, `SALASANA`, `NIMI`, `KAYNTIOSOITE`, `LASKUTUSOSOITE`, `PUHELINNUMERO`, `SAHKOPOSTI`, `ASUNTOTYYPPI`, `PINTAALA`, `TONTTIKOKO`, `LUONTIPVM`) VALUES
  (3, 'maija1', 'salasana', 'Maija Meikalainen', 'Asuntokatu 5 C 2', 'Asuntokatu 5 C 2', '044 4442211', 'maija.meikalainen@joku.fi' ,'kerrostalo', '30m^2', '-', '16-09-2013');

CREATE TABLE IF NOT EXISTS `TYOTILAUKSET` (
  `AVAIN` int(11) NOT NULL AUTO_INCREMENT,
  `TILAAJA` varchar(50) NOT NULL,
  `KUVAUS` varchar(50) NOT NULL,
  `TILAUSPVM` varchar(10) NOT NULL,
  `ALOITUSPVM` varchar(10) NOT NULL,
  `VALMISTUMISPVM` varchar(10) NOT NULL,
  `HYVAKSYMISPVM` varchar(10) NOT NULL,
  `TYOKOMMENTTI` varchar(200) NOT NULL,
  `TUNTIMAARA` int(200) NOT NULL,
  `TARVIKKEET` varchar(200) NOT NULL,
  `KUSTANNUSARVIO` varchar(50) NOT NULL,
  `STATUS` varchar(15) NOT NULL,
  PRIMARY KEY (`AVAIN`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

  INSERT INTO `TYOTILAUKSET` (`AVAIN`, `TILAAJA`, `KUVAUS`, `TILAUSPVM`, `ALOITUSPVM`, `VALMISTUMISPVM`, `HYVAKSYMISPVM`, `TYOKOMMENTTI`, `TUNTIMAARA`, `TARVIKKEET`, `KUSTANNUSARVIO`, `STATUS`) VALUES
  (1, 'matti1', 'bla bla bla', '16-09-2013', '', '', '', '', 0, '', '', 'TILATTU');
  INSERT INTO `TYOTILAUKSET` (`AVAIN`, `TILAAJA`, `KUVAUS`, `TILAUSPVM`, `ALOITUSPVM`, `VALMISTUMISPVM`, `HYVAKSYMISPVM`, `TYOKOMMENTTI`, `TUNTIMAARA`, `TARVIKKEET`, `KUSTANNUSARVIO`, `STATUS`) VALUES
  (2, 'matti1', 'bla bla bla', '15-09-2013', '18-09-2013', '', '', '', 0, '', '', 'ALOITETTU');
  INSERT INTO `TYOTILAUKSET` (`AVAIN`, `TILAAJA`, `KUVAUS`, `TILAUSPVM`, `ALOITUSPVM`, `VALMISTUMISPVM`, `HYVAKSYMISPVM`, `TYOKOMMENTTI`, `TUNTIMAARA`, `TARVIKKEET`, `KUSTANNUSARVIO`, `STATUS`) VALUES
  (3, 'maija1', 'Talkootyo osoitteessa Asuntokatu 5 C 2', '16-09-2013', '18-09-2013', '19-09-2013', '20-09-2013', '-', 13, 'Jatesakkeja, haravoita jne.', '300 euroa', 'HYVAKSYTTY');

CREATE TABLE IF NOT EXISTS `TARJOUSPYYNNOT` (
  `AVAIN` int(11) NOT NULL AUTO_INCREMENT,
  `TILAAJA` varchar(50) NOT NULL,
  `KUVAUS` varchar(50) NOT NULL,
  `JATTAMISPVM` varchar(10) NOT NULL,
  `VASTAAMISPVM` varchar(10) NOT NULL,
  `KUSTANNUSARVIO` varchar(200) NOT NULL,
  `STATUS` varchar(15) NOT NULL,
  PRIMARY KEY (`AVAIN`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

  INSERT INTO `TARJOUSPYYNNOT` (`AVAIN`, `TILAAJA`, `KUVAUS`, `JATTAMISPVM`, `VASTAAMISPVM`, `KUSTANNUSARVIO`, `STATUS`) VALUES
  (1, 'maija1', 'Lumen kolaaminen ja pihan yllapito talvella.', '27-09-2013', '', '', 'JATETTY');
  INSERT INTO `TARJOUSPYYNNOT` (`AVAIN`, `TILAAJA`, `KUVAUS`, `JATTAMISPVM`, `VASTAAMISPVM`, `KUSTANNUSARVIO`, `STATUS`) VALUES
  (2, 'matti1', 'Vessan laatoitus osoitteessa Jokukatu 16', '05-09-2013', '13-09-2013', '1200 euroa', 'VASTATTU');